---
output:
  sort-results: true

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    # - depguard
    - gofumpt
    - goimports
    - revive
    - bodyclose
    # - gochecknoglobals
    - errname
    - errorlint
    - forcetypeassert
    - gochecknoinits
    - gocyclo
    - gosec
    - misspell
    - promlinter
    - prealloc
    - sqlclosecheck
    - sloglint
    - bodyclose
    - importas
    - spancheck
    - usestdlibvars
    # - wrapcheck

linters-settings:
  revive:
    enable-all-rules: true
    ignore-generated-header: true
    rules:
      - name: line-length-limit
        arguments: [160]
      - name: function-length
        arguments: [50, 150] # Maximum number of lines allowed in a function
      - name: cognitive-complexity
        arguments: [12]
      - name: cyclomatic
        arguments: [12]
  sloglint:
    no-global: "all"
    key-naming-case: snake
