---
version: "2"

linters:
  enable:
    - staticcheck
    - bodyclose
    - errname
    - errorlint
    - forcetypeassert
    - gochecknoinits
    - gocyclo
    - gosec
    - importas
    - misspell
    - prealloc
    - promlinter
    - revive
    - sloglint
    - spancheck
    - sqlclosecheck
    - usestdlibvars
  settings:
    revive:
      enable-all-rules: true
      rules:
        - name: line-length-limit
          arguments:
            - 160
        - name: function-length
          arguments:
            - 70
            - 200
        - name: cognitive-complexity
          arguments:
            - 12
        - name: cyclomatic
          arguments:
            - 12
    sloglint:
      no-global: all
      static-msg: true
      key-naming-case: snake
      args-on-sep-lines: true
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$

formatters:
  enable:
    - gofumpt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
