---
output:
  sort-results: true

linters:
  enable:
    # - depguard
    - gofumpt
    - goimports
    - revive
    - bodyclose
    # - gochecknoglobals
    - errname
    - errorlint
    # - forcetypeassert
    - gochecknoinits
    - gocyclo
    - gosec
    - misspell
    - promlinter
    - prealloc
    - sqlclosecheck

linters-settings:
  revive:
    enable-all-rules: true
    ignore-generated-header: true
    rules:
      - name: line-length-limit
        arguments: [160]
      - name: function-length
        arguments: [50, 150] # Maximum number of lines allowed in a function
      - name: cognitive-complexity
        arguments: [12]
      - name: cyclomatic
        arguments: [12]
  errcheck:
    exclude-functions:
      - (github.com/go-kit/log.Logger).Log
