---
name: postgres_exporter
x-postgres: &postgres
  environment:
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: postgres
    POSTGRES_DB: postgres
  ports:
    - "5432:5432"
  command: ["postgres", "-c", "config_file=/etc/postgresql/postgresql.conf"]
  healthcheck:
    test: ["CMD-SHELL", "pg_isready -U postgres"]
    interval: 5s
    timeout: 5s
    retries: 5
  networks:
    postgres_exporter:
      aliases:
        - postgres

x-network: &network
  networks:
    - postgres_exporter

services:
  postgres13:
    <<: *postgres
    image: postgres:13.23@sha256:4689940c683801b4ab839ab3b0a0a3555a5fe425371422310944e89eca7d8068
    volumes:
      - postgres_data_13:/var/lib/postgresql/data
      - ./docker/postgresql.conf:/etc/postgresql/postgresql.conf
    profiles:
      - postgres13

  postgres14:
    <<: *postgres
    image: postgres:14.22@sha256:bbb8851608e3ff4901156bf6a4bf90735a9d44ae014c03811bfdb2f9c354b18b
    volumes:
      - postgres_data_14:/var/lib/postgresql/data
      - ./docker/postgresql.conf:/etc/postgresql/postgresql.conf
    profiles:
      - postgres14

  postgres15:
    <<: *postgres
    image: postgres:15.17@sha256:c635fa3e3b7421a659d34abdfd6d492f679cbe8149e261a501237b55c5a94212
    volumes:
      - postgres_data_15:/var/lib/postgresql/data
      - ./docker/postgresql.conf:/etc/postgresql/postgresql.conf
    profiles:
      - postgres15

  postgres16:
    <<: *postgres
    image: postgres:16.13@sha256:2586e2a95d1c9b31cb2967feb562948f7d364854453d703039b6efa45fe48417
    volumes:
      - postgres_data_16:/var/lib/postgresql/data
      - ./docker/postgresql.conf:/etc/postgresql/postgresql.conf
    profiles:
      - postgres16

  postgres17:
    <<: *postgres
    image: postgres:17.9@sha256:b994732fcf33f73776c65d3a5bf1f80c00120ba5007e8ab90307b1a743c1fc16
    volumes:
      - postgres_data_17:/var/lib/postgresql/data
      - ./docker/postgresql.conf:/etc/postgresql/postgresql.conf
    profiles:
      - postgres17

  postgres18:
    <<: *postgres
    image: postgres:18.3@sha256:a9abf4275f9e99bff8e6aed712b3b7dfec9cac1341bba01c1ffdfce9ff9fc34a
    volumes:
      - postgres_data_18:/var/lib/postgresql/data
      - ./docker/postgresql.conf:/etc/postgresql/postgresql.conf
    profiles:
      - postgres18

  prometheus:
    <<: *network
    image: quay.io/prometheus/prometheus:v3.11.0@sha256:131bf4c9d8a0337782ea8b753249f4903afac01379f3cced87ceaf8ca82ab9f3
    ports:
      - "9090:9090"
    volumes:
      - ./docker/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/docker/prometheus_data
    profiles:
      - default

  postgres-exporter:
    <<: *network
    build:
      context: .
    command:
      [
        "--log.level=debug",
        "--log.format=logfmt",
        "--db.excluded-databases=rdsadmin",
        "--db.excluded-databases=cloudsqladmin",
      ]
    entrypoint: ["/bin/postgres_exporter"]
    ports:
      - "9187:9187"
    environment:
      - PGHOST=postgres
      - PGUSER=postgres
      - PGPASSWORD=postgres
      - PGPGDATABASE=postgres
      - PGSSLMODE=disable
    profiles:
      - default

  grafana:
    <<: *network
    image: grafana/grafana:12.4.3@sha256:2e986801428cd689c2358605289c90ab37d2b39e24808874971f54c99bcdc412
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - grafana_data:/var/lib/grafana
      - ./docker/grafana/provisioning:/etc/grafana/provisioning
      - ./docker/grafana/dashboards:/etc/grafana/dashboards
    depends_on:
      - prometheus
    profiles:
      - default

volumes:
  prometheus_data:
  grafana_data:
  postgres_data_13:
  postgres_data_14:
  postgres_data_15:
  postgres_data_16:
  postgres_data_17:
  postgres_data_18:

networks:
  postgres_exporter:
