---
name: postgres_exporter
x-postgres: &postgres
  environment:
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: postgres
    POSTGRES_DB: postgres
  ports:
    - "5432:5432"
  command: ["postgres", "-c", "config_file=/etc/postgresql/postgresql.conf"]
  healthcheck:
    test: ["CMD-SHELL", "pg_isready -U postgres"]
    interval: 5s
    timeout: 5s
    retries: 5
  networks:
    postgres_exporter:
      aliases:
        - postgres

x-network: &network
  networks:
    - postgres_exporter

services:
  postgres13:
    <<: *postgres
    image: postgres:13.23@sha256:4689940c683801b4ab839ab3b0a0a3555a5fe425371422310944e89eca7d8068
    volumes:
      - postgres_data_13:/var/lib/postgresql/data
      - ./docker/postgresql.conf:/etc/postgresql/postgresql.conf
    profiles:
      - postgres13

  postgres14:
    <<: *postgres
    image: postgres:14.22@sha256:705a5d5b5836f3fcba0d02c4d281e6a7dd9ed2dd4078640f08a1e1e9896e097d
    volumes:
      - postgres_data_14:/var/lib/postgresql/data
      - ./docker/postgresql.conf:/etc/postgresql/postgresql.conf
    profiles:
      - postgres14

  postgres15:
    <<: *postgres
    image: postgres:15.17@sha256:f30e3de0ac9cc938dac627ef2231099867c694b5f949fadb924c8c977428c399
    volumes:
      - postgres_data_15:/var/lib/postgresql/data
      - ./docker/postgresql.conf:/etc/postgresql/postgresql.conf
    profiles:
      - postgres15

  postgres16:
    <<: *postgres
    image: postgres:16.13@sha256:78df81b1442dcc764c1104154da7162635e40cfffe67579c42a1c1b96dfc209c
    volumes:
      - postgres_data_16:/var/lib/postgresql/data
      - ./docker/postgresql.conf:/etc/postgresql/postgresql.conf
    profiles:
      - postgres16

  postgres17:
    <<: *postgres
    image: postgres:17.9@sha256:2cd82735a36356842d5eb1ef80db3ae8f1154172f0f653db48fde079b2a0b7f7
    volumes:
      - postgres_data_17:/var/lib/postgresql/data
      - ./docker/postgresql.conf:/etc/postgresql/postgresql.conf
    profiles:
      - postgres17

  postgres18:
    <<: *postgres
    image: postgres:18.3@sha256:69e8582b781cb44fa4557b98ed586fe68361e320d9b12f9707494335634f4f3d
    volumes:
      - postgres_data_18:/var/lib/postgresql/data
      - ./docker/postgresql.conf:/etc/postgresql/postgresql.conf
    profiles:
      - postgres18

  prometheus:
    <<: *network
    image: quay.io/prometheus/prometheus:v3.10.0@sha256:7571a304e67fbd794be02422b13627dc7de822152f74e99e2bef95d29eceecde
    ports:
      - "9090:9090"
    volumes:
      - ./docker/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/docker/prometheus_data
    profiles:
      - default

  postgres-exporter:
    <<: *network
    build:
      context: .
    command:
      [
        "--log.level=debug",
        "--log.format=logfmt",
        "--db.excluded-databases=rdsadmin",
        "--db.excluded-databases=cloudsqladmin",
      ]
    entrypoint: ["/bin/postgres_exporter"]
    ports:
      - "9187:9187"
    environment:
      - PGHOST=postgres
      - PGUSER=postgres
      - PGPASSWORD=postgres
      - PGPGDATABASE=postgres
      - PGSSLMODE=disable
    profiles:
      - default

  grafana:
    <<: *network
    image: grafana/grafana:12.4.1@sha256:e932bd6ed0e026595b08483cd0141e5103e1ab7ff8604839ff899b8dc54cabcb
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - grafana_data:/var/lib/grafana
      - ./docker/grafana/provisioning:/etc/grafana/provisioning
      - ./docker/grafana/dashboards:/etc/grafana/dashboards
    depends_on:
      - prometheus
    profiles:
      - default

volumes:
  prometheus_data:
  grafana_data:
  postgres_data_13:
  postgres_data_14:
  postgres_data_15:
  postgres_data_16:
  postgres_data_17:
  postgres_data_18:

networks:
  postgres_exporter:
