global:
  scrape_interval: 10s
  scrape_timeout: 1s
  evaluation_interval: 10s

  external_labels:
    monitor: "postgres-exporter"

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
  - job_name: "postgres"
    static_configs:
      - targets: ["postgres-exporter:9187"]
