global:
  scrape_interval: 10s
  scrape_timeout: 1s
  evaluation_interval: 10s

  external_labels:
    monitor: "postgres-exporter"

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
  - job_name: "postgres"
    static_configs:
      - targets: ["postgres-exporter:9187"]
  - job_name: "postgres_replication_main"
    static_configs:
      - targets: ["postgres-exporter-main:9187"]
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: postgres_main
  - job_name: "postgres_replication_replica"
    static_configs:
      - targets: ["postgres-exporter-replica:9187"]
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: postgres_replica
